### ISSUE TITLE
cuda memory allocation error when running in container

### ISSUE THREAD

**Issue by rory-bedford** [lsb-riken/CUBIC-informatics#18]
Hi,

I'm using the container method to run CUBIC. It seems to build just find. I'm trying to run on the 100 image test dataset. I'm running on two rtx2080ti GPUs, and set CUDA_NVCC_FLAGS=7.5 to match this GPU when building the container. I also have 40GB RAM allocated.

For some reason, I keep getting the following error:

CUDA error at /workdir/src/3D/HDoG3D_main.cpp:93 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void **)&d_cub_tmp, p.cub_tmp_bytes)"

Can anyone help me out?

Many thanks,
Rory

**Comment by s-horiguchi** [comment]
Hi Rory,

It is an error in allocating memory on GPU.
Since your GPU seems to have enough memory size, I suspect that a part of the memory is used by other applications, e.g., graphics output, and the available size is less than required.
You can check the memory usage by running nvidia-smi command.

Hope this helps!

**Comment by rory-bedford** [comment]
I'm actually running cubic on a GPU cluster node, and allocating the memory manually so the memory should be completely unused. I'm also building cubic with the correct NVCC_FLAG for the cluster gpus i'm using, and additionally loading cuda/11.6 in my sbatch script before running cubic, so i'm quite lost as to what's going wrong here.

Thanks for the help!

**Comment by s-horiguchi** [comment]
Hmm...
Since it is the last GPU memory allocation in the code, other allocations before this line must be fine. If so, it is likely that your GPU is somehow running out of memory.
To make sure of this point, what happens if you set the `depth` parameter to a smaller value?
The `param_test_RV.json` will become something like this: (depth was 32 originally)
```
{
    ...
    "HDoG_param": {
        "#": "the number of images to be processed at once",
        "depth": 16,
        "#": "the number of discarded images because of poor quality",
        "extra_depth_margin": 3,

        ...
    },
}
```
It may produce another error at runtime (or maybe not. I am not sure). But if you get a different error or result, it means you successfully passed the memory allocation with a smaller size.
